sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t yxlee245/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yxlee245/docker-react npm run test